accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.contrib import admin

from accounts.views import signup


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ReceiptListView,
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings


# Create your models here.



class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):      # a method that returns the name value
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name 


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(decimal_places=3, max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateField()       # a date property that contains a date when the transaction took place
    
    purchaser = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        "ExpenseCategory",
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    account = models.ForeignKey(
        "Account",
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True
    )
    

accounts/views.py
from msilib.schema import ListView
from urllib import request
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login

# Create your views here.


def signup(request):
    if request.method == "POST":  # if the request method is "POST", then
        form = UserCreationForm(request.POST)  # create a form
        if form.is_valid():  # if the form is valid, then
            username = request.POST.get(
                "username"
            )  # the 'username'value from the request.POST dictionary
            password = request.POST.get(
                "password1"
            )  # the 'password1' value from the request.POST dictionary
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()  # save the user object
            login(
                request, user
            )  # login the user with the request and user object
            return redirect("home")  # return a redirect to the "home" path
    else:  # otherwise,
        form = UserCreationForm(request.POST)
        context = {  # context = dictionary with key
            "form": form,  # "form" and value form
        }
    return render(
        request, "registration/signup.html", context
    )  # return render with request, "registration/signup.html", and the context

receipts/views.py
from django.shortcuts import redirect
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView


from receipts.models import Receipt, Account, ExpenseCategory

# Create your views here.

class AccountCreateView(CreateView):
    model = Account
    template_name = "accounts/create.html"
    fields = ["name", "number"]

    def form_valid(self, form):         
        item = form.save(commit=False)          # automatically assign the current user
        item.owner = self.request.user  # to the appropriate User proeprty
        item.save()
        return redirect("list_accounts")


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):    # To access any list view, a person must be logged in
    model = ExpenseCategory
    template_name = "expense_categories/create.html"
    fields = ["name"]

    def form_valid(self, form):         
            item = form.save(commit=False)          # automatically assign the current user
            item.owner = self.request.user  # to the appropriate User proeprty
            item.save()
            return redirect("list_categories")    


class ReceiptCreateView(CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "purchaser","category", "account"]

    def form_valid(self, form):         
                item = form.save(commit=False)          # automatically assign the current user
                item.purchaser = self.request.user  # to the appropriate User proeprty
                item.save()
                return redirect("home") 




class AccountListView(LoginRequiredMixin, ListView):    # To access any list view, a person must be logged in
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self): #display the data in tables. Be sure to filter the data for only the current user
        return Account.objects.filter(owner=self.request.user)    # Refer to the model and user_property that is a foreign key to the object


class ExpenseCategoryListView(LoginRequiredMixin, ListView):    # To access any list view, a person must be logged in
    model = ExpenseCategory
    template_name = "expense_categories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class ReceiptListView(LoginRequiredMixin, ListView):    # To access any list view, a person must be logged in
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user,)
    

receipts/templates/accounts/create.html
{% extends 'base.html' %} {% block content %} {% endblock content %}

receipts/templates/accounts/list.html
{% extends 'base.html' %} {% block content %} 

<main>
    <h1>Accounts</h1>
    <div>
        <table>
            <tr>
                <th>Name</th>
                <th>Number</th>
                <th>Number of Receipts</th>
            </tr>
            <thead>
            <tbody>
                    {% for account in account_list %}
                    <tr>
                        <td>{{ account.name }}</td>
                        <td>{{ account.number }}</td>
                        <td>{{ account.receipts.all|length }}</td>
                    </tr>
                    {% endfor %}
            </tbody>
            </thead>
        </table>
    </div>
</main>
{% endblock content %}

receipts/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="style.css" />
    <title>{% block title %}{% endblock %}</title>
  </head>

  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <div>
            <a href="{% url 'logout' %}">Logout</a>
          </div>
          {% else %}
          <div>
            <a href="{% url 'signup' %}">Sign Up</a>
          </div>
          <div>
            <a href="{% url 'login' %}">Login</a>
          </div>
          {% endif %}
        </ul>
      </nav>
    </header>
  </body>
  {% block content %} {% endblock %}
</html>

receipts/templates/expense_categories/create.html
{% extends 'base.html' %} {% block content %} {% endblock content %}

receipts/templates/expense_categories/list.html
{% extends 'base.html' %} {% block content %}

<main>
    <h1>Expense Category</h1>
    <div>
        <table>
            <tr>
                <th>Name</th>
                <th>Number of Receipts</th>
            </tr>
            <thead>
            <tbody>
                {% for category in expense_categories_list %}
                <tr>
                    <td>{{ category.name }}</td>
                    <td>{{ category.receipts.all|length }}</td>
                </tr>
                {% endfor %}
            </tbody>
            </thead>
        </table>
    </div>
</main>
 {% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %} {% block content %} {% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %} {% block content %} 

<main>
    <h1>Receipts</h1>
    <div>
        <table>
            <tr>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Date</th>
                <th>Category</th>
                <th>Account</th>
            </tr>
            <thead>
            <tbody>
                {% for receipt in receipt_list %}
                <tr>
                    <td>{{ receipt.vendor }}</td>
                    <td>{{ receipt.total }}</td>
                    <td>{{ receipt.tax }}</td>
                    <td>{{ receipt.date|date:"m-d-Y" }}</td>
                    <td>{{ receipt.category.name }}</td>
                    <td>{{ receipt.account.name }}</td>
                </tr>
                {% endfor %}
            </tbody>
            </thead>
        </table>
    </div>
</main>
{% endblock content %}